apiVersion: v1
kind: Service
metadata:
  name: expense-service
  namespace: expense-tracker
spec:
  selector:
    app: expense-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP

