apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: expense-tracker

resources:
  - namespace.yaml
  - configmaps.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - rabbitmq.yaml
  - auth-deployment.yaml
  - auth-service.yaml
  - expense-deployment.yaml
  - expense-service.yaml
  - category-deployment.yaml
  - category-service.yaml
  - report-deployment.yaml
  - report-service.yaml
  - hpa.yaml
  - ingress.yaml

