apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: expense-tracker

resources:
  - prometheus/prometheus-rbac.yaml
  - prometheus/prometheus-config.yaml
  - prometheus/prometheus-deployment.yaml
  - grafana/grafana-secret.yaml
  - grafana/grafana-deployment.yaml
  - grafana/grafana-datasources.yaml
  - grafana/grafana-dashboards.yaml

